### ISSUE TITLE
nx monorepo and developer ground work

### ISSUE THREAD

**Issue by konne** [easyBSB/easyBSB#1]
- [x] @easybsb/parser (main bsb protocol) 
- [x] @easybsb/server (nestJS 8 REST API) 
- [x] @easybsb/web (angular frontend) 

- [ ] ~~Unit Tests~~
- [x] e2e test (playwright)

- [x] TypeORM & sql.js
  -    added devices with
        - connection for each device (serial with port, TCP)
        - heater settings
        - favourite settings
- [ ] API token (read / readwrite)
- [x] Authentication

**Developer experience**
- [x] GitPod

**OUTPUT**
- [x] npm package @parser
- [x] docker images (contains core, server & web)
- [x] electron app    (contains core, server & web)

**Comment by r-hannuschka** [comment]
vue currently not working very good, i try to use vue-plus but this is not compatible together with nx@13, an bigger update will come maybe some time they working on it last update was on january.

There is another library out i found, but this one try to install picolors, a package what not exists on npm i think it is a private one and failed completly after this. Also installed a ton of dependencies i do not know we really want it. So i skip it.

So for this now i just kick vue and used angular for that reasons above.

**Comment by konne** [comment]
@r-hannuschka updated ticket
