### ISSUE TITLE
authenticate & authorize

### ISSUE THREAD

**Issue by konne** [easyBSB/easyBSB#17]
https://docs.nestjs.com/security/authentication

https://docs.nestjs.com/security/authorization#integrating-casl

with roles:
Admin -> Manger + manage connections + usermanagement and change roles
Manager -> can change BSB values
Viewer -> only view

**Comment by r-hannuschka** [comment]
[ ] simple login page
[ ] e2e tests

**Comment by r-hannuschka** [comment]
[ ] simple login page
[ ] e2e tests
