### ISSUE TITLE
electron app name

### ISSUE THREAD

**Issue by konne** [easyBSB/easyBSB#208]
the electron app name was easybsb and is now server-0.0.1....

![image](https://user-images.githubusercontent.com/1100969/172315995-5870d300-b2e0-4741-b3d7-a1e42fdf080a.png)

please change it to easybsb

**Comment by r-hannuschka** [comment]
Mhm super strange, for me it is still easy-bsb from name. I think something happens with your build, cache issue i got the same one time and then never again.

just to be sure run all commands again

`npm run build:all`
`npm run package:server`
`npm run package:electron`
